// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpanishDayAhead.Infrastructure.Persistence;

#nullable disable

namespace SpanishDayAhead.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpanishDayAheadDbContext))]
    [Migration("20260710165436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SpanishDayAhead.Domain.DayAheadPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BiddingZone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeliveryStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceEurPerMWh")
                        .HasColumnType("REAL");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate")
                        .HasDatabaseName("IX_DayAheadPrices_DeliveryDate");

                    b.HasIndex("DeliveryStartUtc")
                        .HasDatabaseName("IX_DayAheadPrices_DeliveryStartUtc");

                    b.HasIndex("BiddingZone", "DeliveryStartUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_DayAheadPrices_BiddingZone_DeliveryStartUtc");

                    b.ToTable("DayAheadPrices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
